Adapt OSX

diff --git a/_zshrc b/_zshrc
--- a/_zshrc
+++ b/_zshrc
@@ -26,7 +26,8 @@ fi
 ###############################################################################
 
 # colors for ls. Also, human-readable sizes are great.
-alias ls='ls -b -CF -h --color=auto'
+#alias ls='ls -b -CF -h --color=auto'
+alias ls='ls -bGFh'
 
 # don't grep in binary files by default
 alias grep='grep -I'
@@ -110,7 +111,9 @@ SAVEHIST=10000
 autoload -U colors && colors
 
 # support colors in ls
-eval $(dircolors -b)
+if [[ $(uname) != "Darwin" ]]; then
+    eval $(dircolors -b)
+fi
 
 # support colors in less
 export LESS_TERMCAP_mb=$'\e[01;31m'
@@ -270,27 +273,46 @@ zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' \
 
 
 ###############################################################################
+#     HELPERS
+###############################################################################
+
+function try_load() {
+    local name="$1"
+    shift
+
+    for p in $*; do
+        [[ -f "$p" ]] && source "$p" && unset p && return
+    done
+
+    unset p
+    echo "Failed to load $name" >&2
+}
+
+
+###############################################################################
 #     VIRTUALENV
 ###############################################################################
 
-VIRTUAL_ENV_DISABLE_PROMPT=1
+if [[ -e "/usr/bin/virtualenvwrapper.sh" ]]; then
+    VIRTUAL_ENV_DISABLE_PROMPT=1
 
-virtualenv_prompt() {
-    if [[ -n $VIRTUAL_ENV ]]; then
-        _virtualenv_prompt="%{${fg_no_bold[magenta]}%}(%{${fg_bold[white]}%}⚑$(basename $VIRTUAL_ENV)%{${fg_no_bold[magenta]}%})%{$reset_color%}"
-    fi
-}
+    virtualenv_prompt() {
+        if [[ -n $VIRTUAL_ENV ]]; then
+            _virtualenv_prompt="%{${fg_no_bold[magenta]}%}(%{${fg_bold[white]}%}⚑$(basename $VIRTUAL_ENV)%{${fg_no_bold[magenta]}%})%{$reset_color%}"
+        fi
+    }
 
-add-zsh-hook precmd virtualenv_prompt
+    add-zsh-hook precmd virtualenv_prompt
 
-source /usr/bin/virtualenvwrapper.sh
+    source /usr/bin/virtualenvwrapper.sh
 
-cd () {
-    builtin cd $*
-    if [[ -f .venv ]]; then
-        workon "$(cat .venv)"
-    fi
-}
+    cd () {
+        builtin cd $*
+        if [[ -f .venv ]]; then
+            workon "$(cat .venv)"
+        fi
+    }
+fi
 
 
 ###############################################################################
@@ -354,99 +376,108 @@ zmodload -ap zsh/mapfile mapfile
 # zmv for batch renaming/moving
 autoload -U zmv
 
-# Start ssh-agent if not running already
-SSH_ENV="$HOME/.ssh/environment"
+# ssh agent
+if [[ $(uname) != "Darwin" ]]; then
+    # Start ssh-agent if not running already
+    SSH_ENV="$HOME/.ssh/environment"
 
-function start_ssh_agent {
-    echo "Starting new SSH agent..."
-    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
-    chmod 600 "${SSH_ENV}"
-    . "${SSH_ENV}" > /dev/null
-}
-
-if [ -f "${SSH_ENV}" ]; then
-    . "${SSH_ENV}" > /dev/null
-    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
-        start_ssh_agent;
+    function start_ssh_agent {
+        echo "Starting new SSH agent..."
+        /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
+        chmod 600 "${SSH_ENV}"
+        . "${SSH_ENV}" > /dev/null
     }
-else
-    start_ssh_agent;
-fi
 
-ssh-add -l >/dev/null || alias ssh='ssh-add -l >/dev/null || ssh-add && unalias ssh; ssh'
+    if [ -f "${SSH_ENV}" ]; then
+        . "${SSH_ENV}" > /dev/null
+        ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
+            start_ssh_agent;
+        }
+    else
+        start_ssh_agent;
+    fi
+
+    ssh-add -l >/dev/null || alias ssh='ssh-add -l >/dev/null || ssh-add && unalias ssh; ssh'
+fi
 
 
 ###############################################################################
 #     fzf
 ###############################################################################
 
-source /usr/share/fzf/key-bindings.zsh
+try_load fzf \
+    /usr/share/fzf/key-bindings.zsh \
+    /usr/local/opt/fzf/shell/key-bindings.zsh
 bindkey '^P' fzf-file-widget
+
 
 ###############################################################################
 #     Google Cloud SDK
 ###############################################################################
 
-# The next line enables shell command completion for gcloud.
-source '/home/lnqs/.local/opt/google-cloud-sdk/completion.zsh.inc'
-
-# And for kubectl
-source <(kubectl completion zsh)
+if [[ -e "${HOME}/.local/opt/google-cloud-sdk/completion.zsh.inc" ]]; then
+    source "${HOME}/.local/opt/google-cloud-sdk/completion.zsh.inc"
+    source <(kubectl completion zsh)
+fi
 
 
 ###############################################################################
 #     KUBEENV
 ###############################################################################
 
-KUBEENV_DISABLE_PROMPT=1
+if [[ -e "${HOME}/Projects/kubeenv/kubeenv.sh" ]]; then
+    KUBEENV_DISABLE_PROMPT=1
 
-kubeenv_prompt() {
-    if [[ -n $KUBEENV ]]; then
-        _kubeenv_prompt="%{${fg_no_bold[cyan]}%}(%{${fg_bold[white]}%}웃$KUBEENV%{${fg_no_bold[cyan]}%})%{$reset_color%}"
-    fi
-}
+    kubeenv_prompt() {
+        if [[ -n ${KUBEENV} ]]; then
+            _kubeenv_prompt="%{${fg_no_bold[cyan]}%}(%{${fg_bold[white]}%}웃$KUBEENV%{${fg_no_bold[cyan]}%})%{$reset_color%}"
+        fi
+    }
 
-add-zsh-hook precmd kubeenv_prompt
+    add-zsh-hook precmd kubeenv_prompt
 
-source "$HOME/Projects/kubeenv/kubeenv.sh"
-source "$HOME/Projects/kubeenv/completion.bash"
+    source "${HOME}/Projects/kubeenv/kubeenv.sh"
+    source "${HOME}/Projects/kubeenv/completion.bash"
+fi
 
 
 ###############################################################################
 #     AWSENV
 ###############################################################################
 
-AWSENV_DISABLE_PROMPT=1
+if [[ -e "${HOME}/Projects/awsenv/awsenv.sh" ]]; then
+    AWSENV_DISABLE_PROMPT=1
 
-awsenv_prompt() {
-    if [[ -n $AWS_PROFILE ]]; then
-        _awsenv_prompt="%{${fg_no_bold[cyan]}%}(%{${fg_bold[white]}%}웃$AWS_PROFILE%{${fg_no_bold[cyan]}%})%{$reset_color%}"
-    fi
-}
+    awsenv_prompt() {
+        if [[ -n ${AWS_PROFILE} ]]; then
+            _awsenv_prompt="%{${fg_no_bold[cyan]}%}(%{${fg_bold[white]}%}웃$AWS_PROFILE%{${fg_no_bold[cyan]}%})%{$reset_color%}"
+        fi
+    }
 
-add-zsh-hook precmd awsenv_prompt
+    add-zsh-hook precmd awsenv_prompt
 
-source "$HOME/Projects/awsenv/awsenv.sh"
-source "$HOME/Projects/awsenv/completion.bash"
-
-
-###############################################################################
-#     NativeScript
-###############################################################################
-
-###-tns-completion-start-###
-if [ -f /home/lnqs/.tnsrc ]; then
-    source /home/lnqs/.tnsrc
+    source "${HOME}/Projects/awsenv/awsenv.sh"
+    source "${HOME}/Projects/awsenv/completion.bash"
 fi
-###-tns-completion-end-###
 
+
+###############################################################################
+#     NATIVE SCRIPT
+###############################################################################
+
+if [ -f "${HOME}/.tnsrc" ]; then
+    source "${HOME}/.tnsrc"
+fi
 
 ###############################################################################
 #     AUTOSUGGESTIONS
 ###############################################################################
 
 # aur/zsh-autosuggestions
-source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
+
+try_load zsh-autosuggestions \
+    /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh \
+    /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
 
 
 ###############################################################################
@@ -456,6 +487,9 @@ source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
 # has to stay at the end of the file
 # community/zsh-syntax-highlighting
 
-source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
+try_load zsh-syntax-highlighting \
+    /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh \
+    /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
+
 ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
 
